# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - julia: nightly
    - os: osx
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Helpers"); Pkg.test("Helpers"; coverage=true)'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hdf5-tools python-numpy python-scipy python-matplotlib
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Helpers")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Helpers")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # Documenter
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Helpers")); include(joinpath("docs", "make.jl"))'
