name = "Helpers"
uuid = "4de40672-05fc-5661-aad9-eb3e0bf5aa76"
authors = ["Carsten Bauer <crstnbr@gmail.com>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"

[compat]
HDF5 = "0.12"
JLD = "0.9"
julia = "1"